* Diss: Dired Image Slideshow
  :PROPERTIES:
  :ID:       c6336377-321e-44fb-967f-c9d757b1ce84
  :END:

  Diss is a full-featured image slideshow for Emacs, based on Dired
  and =image-mode=.

** Features
   :PROPERTIES:
   :ID:       9aa39291-4b5f-44ad-a0aa-6449dcd90b21
   :END:

   - Use any Dired buffer (including =find-dired=) as the source of
     images.
   - Manual navigation, or automatic advance with delay.
   - Easily categorize files: mark, flag for deletion, or apply an
     arbitrary marker character directly from the image.
   - Advancing images can optionally apply a marker to every image.
   - Infinite loop, or pop back to image list when finished.
   - Multiple slideshow configurations can be named and saved.
   - Quick image tools: Rotate CW/CCW, smart fit, fit height, fit
     width, rename.


** Standard GitHub Disclaimer
   :PROPERTIES:
   :ID:       eb214507-bab1-4eb6-a3a3-b7a558c96d26
   :END:

   This is a read-only mirror to ease discoverability, and no primary
   development work happens on GitHub.


** Installation
   :PROPERTIES:
   :ID:       0b5d0376-da20-4787-925e-62ab369ea5fa
   :END:

   Diss isn’t in any ELPA repositories, so the easiest method of
   installation is to use =straight= and =use-package=:

   #+BEGIN_SRC emacs-lisp
     (use-package diss
       :straight (diss :host github
                       :repo "ieure/diss"))
   #+END_SRC


** Usage
   :PROPERTIES:
   :ID:       94a18a81-8b61-4402-a09e-a3e1f90b19b8
   :END:

   From a Dired buffer, =C-c C-s= will start Diss, prompting for the
   saved configuration to use.  Saved configurations associate a name
   to a set of slideshow parameters, i.e. how many images to advance
   by, whether to loop, whether to automatically advance, etc.  The
   default is ="standard"=, which doesn’t mark, loop or automatically
   advance -- the user controls moving between images.

   Entering the name of a configuration which isn’t already known
   prompts for all Diss parameters and saves it.

   Once Diss has been started, it creates an indirect =*diss ...*=
   buffer and loads the first image.  This also scales the image to
   take up as much of the window as possible, without cropping or
   scrolling.

   These keybindings are available:

   - =n= / =p=: Move to the next/previous image.  Shadows
     =image-next-file= / =image-previous-file=, but uses the Dired
     buffer for the files and order.
   - =N= / =P=: Move to the next/previous image in a new window,
     instead of replacing the visible one.
   - =m=: Mark the current image in the Dired buffer, and advance to
     the next.
   - =d=: Flag for deletion and advance.
   - =u=: Unmark and advance.
   - =r=: Rotate clockwise.  Shadows =image-rotate=.
   - =R=: Rotate counterclockwise.
   - =x=: Resize image to fit window width.
   - =y=: Resize image to fit window height.
   - =f=: Smart fit, resize to the maximum size possible that still
     fits in the current window.
   - =0=: Reset all size/rotation transforms.
   - =SPC=: Pause/unpause slideshow, if it’s auto-advancing.
   - =q=: Bury buffer.  Pauses slideshow if was automatically
     advancing.


*** Advanced use
    :PROPERTIES:
    :ID:       2a63b4b9-5573-415b-8ee7-89116095cc44
    :END:

**** Prefix names
     :PROPERTIES:
     :ID:       13bf771a-7529-4c0b-8341-6282076d523e
     :END:

     Prefix names are a way to give a file a human-readable name,
     while preserving the original.  The file is renamed to have a
     user-given prefix, followed by an underscore, followed by the
     existing filename.

     Pressing =e= will prompt for a prefix name to the currently
     image, and rename it to have it.  If the file already has a
     prefix name, it’s replaced with the entered one.


**** Moving
     :PROPERTIES:
     :ID:       cc19a7fe-7047-4d8c-876a-31b0fb8ba37b
     :END:

     Pressing =v= will prompt for a destination directory, then move
     the current image to it, and advance to the next image.


**** Categorizing and sorting
     :PROPERTIES:
     :ID:       e17604f4-1ba9-4d80-a30f-e5e85d0224d3
     :END:

     Diss can be used to sort large numbers of images.

     Pressing =c= will prompt for a category character, which can be
     any alphanumeric or symbol.  This character is placed on the file
     in the Diss buffer.

     The variable =diss-sort-destinations= (which can be customized)
     is an alist of characters to destination directories.  Pressing
     =C-c C-c= in the Diss buffer (/not/ on the image) will move all
     marked files to the corresponding directories in
     =diss-sort-destinations=.

     Additionally, there’s one special case: If a file has a prefix
     name which matches a destination directory name, and is marked
     with =*=, it will be moved to that destination.  This allows
     images to be marked with =m=, which is more ergonomic than
     pressing =c a= over and over.


** Motivation
   :PROPERTIES:
   :ID:       4bfedd34-44b9-481d-aebb-34dd31febbf3
   :END:

   While there are a number of other Emacs-based ways to deal with
   large numbers of images, they all have significant drawbacks.


*** =image-next-file=
    :PROPERTIES:
    :ID:       271af254-6135-493e-97e0-3819e6a8f9f4
    :END:

    When you open any image in Emacs, =image-mode= binds =n= and =p= to
    =image-next-file= and =image-previous-file=, which allows you to
    navigate to other images in the same directory.

    This is convenient, since it’s built-in, but has numerous
    disadvantages and annoyances:

    - The unsorted output of =directory-files= is used to navigate,
      which means its idea of "next" can be surprising.
    - Only navigates images within the same directory.
    - When you reach the end of images, it silently loops back to the
      start.
    - Poor performance, especially with large directories.  Every time
      you move forward/backward, Emacs reads every file in the current
      directory, compares it to a regex matching image filenames, then
      performs an O(n) search over that subset to find the current
      position.


*** =image-dired-slideshow-start=
    :PROPERTIES:
    :ID:       21de028f-b6c1-48a8-88cb-aaf3dd40de14
    :END:

    This is also built-in.

    - Requires you to enter the number of images to display, rather
      than showing them all, which is weird.
    - It seems to show thumbnails instead of the complete image.
    - Maybe I’m doing it wrong, but I couldn’t get it to automatically
      advance images.


** feh
   :PROPERTIES:
   :ID:       8b7cc089-661e-4d28-9784-e0669bfc22f3
   :END:

   Emacs’ performance with images, especially large ones, is not
   great.  For this reason, Diss has a backend that uses [[https://feh.finalrewind.org/][feh]] to
   display images.

   Currently, *it requires EXWM*.  Breaking this dependency would mean that
   feh can only be used as a viewer, with none of the
   marking/renaming/sorting functionality.  This is likely to happen,
   but unfortunate.

   To enable the feh backend, set =diss--slideshow-class=:

   #+BEGIN_SRC emacs-lisp
     (setq diss--slideshow-class 'diss-feh-slideshow)
   #+END_SRC


** Limitations
   :PROPERTIES:
   :ID:       b1e38bbb-f3f5-448f-91ed-044565d63131
   :END:

   - If you attempt to load a very large image (approximately >
     5000x5000, or 25 megapixels), Emacs will instantly crash.
